workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: YOUR_API_KEY_NAME
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.eio.xullo
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Generate iOS platform files
        script: |
          flutter create --platforms=ios .

      - name: Set iOS Deployment Target to 15.0
        script: |
          # Update Podfile
          if [ -f "ios/Podfile" ]; then
            # Remove any existing platform line
            sed -i '' '/^platform :ios/d' ios/Podfile
            # Add platform :ios, '15.0' at the top after any comments
            sed -i '' "1a\\
  platform :ios, '15.0'\\
  " ios/Podfile
          fi
          
          # Update project.pbxproj for all targets
          find ios -name "project.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' {} \;
  
  echo "✅ iOS deployment target set to 15.0"

- name: Install CocoaPods dependencies
  script: |
    cd ios
    pod install
    cd ..

- name: Flutter build IPA
  script: |
    flutter build ipa --release \
      --export-options-plist=/Users/builder/export_options.plist

artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - flutter_drive.log

publishing:
  email:
    recipients:
      - your-email@example.com
    notify:
      success: true
      failure: true
  app_store_connect:
    auth: integration
    submit_to_testflight: true
    beta_groups:
      - Beta Testers